apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://fluent.github.io/helm-charts'
    targetRevision: '0.43.0'
    chart: fluent-bit
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
